### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by mlliarm** [logtalk-actions/setup-jiprolog#3]
Hello, Paulo,

It seems that the link you're using for the CI for this Prolog has changed from:

```
 /home/runner/work/_actions/logtalk-actions/setup-jiprolog/master/src/install-jiprolog-ubuntu latest
  --2022-01-20 06:20:47--  https://github.com/jiprolog/jiprolog/releases/download/vlatest/JIProlog-latest.zip
  Resolving github.com (github.com)... 192.30.255.113
  Connecting to github.com (github.com)|192.30.255.113|:443... connected.
  HTTP request sent, awaiting response... 404 Not Found
  2022-01-20 06:20:47 ERROR 404: Not Found.
  
  Error: The process '/home/runner/work/_actions/logtalk-actions/setup-jiprolog/master/src/install-jiprolog-ubuntu' failed with exit code 8
```

to:

[https://github.com/jiprolog/jiprolog/releases/download/v4.1.7.1/JIProlog-4.1.7.1.zip](https://github.com/jiprolog/jiprolog/releases/download/v4.1.7.1/JIProlog-4.1.7.1.zip)  (latest version, August 2021).

Cheers!

**Comment by pmoura** [comment]
Thanks for the bug report. Seems that the author of JIProlog didn't created a `latest` tag for the 4.1.7.1 release like he did for previous releases. Should be fixed now.

**Comment by pmoura** [comment]
Not working yet. The fix is correct and JIProlog is now downloaded. But GitHub injects the option `-Djava.awt.headless=true` in the startup command used by Logtalk and that causes an exception in JIProlog.
